<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.fsproj" />
    <ProjectReference Include="..\StreamInfrastructure\StreamInfrastructure.fsproj" />
    <ProjectReference Include="..\StreamSharedServer\StreamSharedServer.fsproj" />

  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="SystemConfig.fs" />
    <Compile Include="Mailbox.fs" />
  </ItemGroup>
  
  
  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.33" />
    <PackageReference Include="Akka.FSharp" Version="1.5.33" />
    <PackageReference Include="Akka.Remote" Version="1.5.33" />
    <PackageReference Include="Akka.Serialization.Hyperion" Version="1.5.33" />
  </ItemGroup>

</Project>

