namespace Tweega.Shared


// client stream types are those required in both UI and web end point
module ClientStreamTypes =
    open System
    open Tweega.Shared.XFrameworkTypes

    type Topic = string
    type TopicSubscription = {ClientRef: ClientRef; Topic: Topic}
    
    
    type DataComplete = option<DateTime>
    
    [<RequireQualifiedAccess>]
    type ActiveStream =
    | Streaming
    | Paused
    | Initialising

    
    
    [<RequireQualifiedAccess>]
    type StreamStatus =
        | Active of ActiveStream * DataComplete * DateTime // * StreamDispose   //function for disposal of generator
        | Terminated of DateTime
        with
        member this.maybeChanged(previousStatus: StreamStatus) =
            match (this, previousStatus) with   //is there a more elegant way to compare 2 DUs?
            | (StreamStatus.Active (ActiveStream.Streaming, Some _, _) ,StreamStatus.Active (ActiveStream.Streaming, Some _, _))
            | (StreamStatus.Active (ActiveStream.Streaming, None, _) , StreamStatus.Active (ActiveStream.Streaming, None, _))
            | (StreamStatus.Active (ActiveStream.Paused, Some _, _) , StreamStatus.Active (ActiveStream.Paused, Some _, _))
            | (StreamStatus.Active (ActiveStream.Paused, None, _) , StreamStatus.Active (ActiveStream.Paused, None, _))
            | (StreamStatus.Active (ActiveStream.Initialising, _, _) , StreamStatus.Active (ActiveStream.Initialising, _, _))
            | (StreamStatus.Terminated _ , StreamStatus.Terminated _) ->
                None
            | _ -> 
                let msg = sprintf "Statuses are CHANGEd from %A to %A" previousStatus this
                printfn "%s" msg  // toConsole is in utils, but we need a lite version of utils that can be included in fable projects tk
                Some this


    type MainstreamTAlias = string
    
    [<RequireQualifiedAccess>]
    type StreamType =
        | PrimitiveTSV of PrimitiveType
        // | PrimitiveList of PrimitiveType
        // | TaggedPrimitiveList of PrimitiveType
        | WriteResult
        | Custom of string


    type SocketID = string
    type StreamID = string //unique identifier for a stream - rename to StreamUID? tk currently created by client but will need to be generated by server and broadcast

    type Options = list<KVP>

    [<RequireQualifiedAccess>]
    type Action = 
        | Add
        | Remove

    type TagParameter = 
        | ResolvedTag of TagAlias
        | UnresolvedTag
    
    let FloatT = (StreamType.PrimitiveTSV PrimitiveType.Float)
    let IntT = (StreamType.PrimitiveTSV PrimitiveType.Int)
    let WriteResultT = StreamType.WriteResult
    
    // are all stream queries actually typed - probably at the UI level.  StreamQuery might just be a server side simplification.  tk


    type DownstreamMessage =
        { Time : DateTime; Message : string }

    type UpstreamMessage =
        { Payload : string }


    type TSVDelivery<'T> = {
        // ServerRef: ServerRef
        ClientRef: ClientRef
        Data: list<TaggedValues<'T>>
    }

    type WSDelivery<'T> = {
        Timestamp: DateTime;
        Delivery: TSVDelivery<'T>
    }

    [<RequireQualifiedAccess>]
    type ClientStreamAPI =
        | TopicSubscribe of list<TopicSubscription> 
        | TopicUnsubscribe of list<TopicSubscription>
        | CloseSocket //OpenSocket?
        | TestMsg of string
    

    type SubscriberID = string

    type FunctionName = string  // name of function as stored by MainstreamT
    type ProviderName = string
    
    type QualifiedFunctionName = {
        Provider: ProviderName;
        Function: FunctionName;
    }

    type QualifiedTag = {
        QFN: QualifiedFunctionName;
        Tag: TagAlias;
    }